// request user's coping skills.
export const REQUEST_CS_USER_PENDING = 'REQUEST_CS_USER_PENDING';
export const REQUEST_CS_USER_SUCCESS = 'REQUEST_CS_USER_SUCCESS';
export const REQUEST_CS_USER_FAILED = 'REQUEST_CS_USER_FAILED';

