// request user's coping skills.
export const REQUEST_CS_USER_PENDING = 'REQUEST_CS_USER_PENDING';
export const REQUEST_CS_USER_SUCCESS = 'REQUEST_CS_USER_SUCCESS';
export const REQUEST_CS_USER_FAILED = 'REQUEST_CS_USER_FAILED';

export const ADD_CS_USER_PENDING = 'ADD_CS_USER_PENDING';
export const ADD_CS_USER_SUCCESS = 'ADD_CS_USER_SUCCESS';
export const ADD_CS_USER_FAILED = 'ADD_CS_USER_FAILED';

export const DELETE_CS_USER_PENDING = 'DELETE_CS_USER_PENDING';
export const DELETE_CS_USER_SUCCESS = 'DELETE_CS_USER_SUCCESS';
export const DELETE_CS_USER_FAILED = 'DELETE_CS_USER_FAILED'

