// Request Daily maintenance task list constants
export const REQUEST_DM_TASKS_PENDING = 'REQUEST_DM_TASKS_PENDING';
export const REQUEST_DM_TASKS_SUCCESS = 'REQUEST_DM_TASKS_SUCCESS';
export const REQUEST_DM_TASKS_FAILED = 'REQUEST_DM_TASKS_FAILED';

// Add task to daily maintenance task list constants
export const REQUEST_ADD_DM_TASK_PENDING = 'REQUEST_ADD_DM_TASK_PENDING';
export const REQUEST_ADD_DM_TASK_SUCCESS = 'REQUEST_ADD_DM_TASK_SUCCESS';
export const REQUEST_ADD_DM_TASK_FAILED = 'REQUEST_ADD_DM_TASK_FAILED';

export const REQUEST_CHECK_DM_TASK_SUCCESS = 'REQUEST_CHECK_DM_TASK_SUCCESS';

export const CHANGE_DM_EDITING = 'CHANGE_DM_EDITING';

export const CHANGE_DM_TASK_TEXT = 'CHANGE_DM_TASK_TEXT';

export const SWAP_DM_TASK_RANKS = 'SWAP_DM_TASK_RANKS';

// Removing dm tasks
export const REMOVE_DM_TASK_PENDING = 'REMOVE_DM_TASK_PENDING';
export const REMOVE_DM_TASK_FAILED = 'REMOVE_DM_TASK_FAILED';
export const REMOVE_DM_TASK_SUCCESS = 'REMOVE_DM_TASK_SUCCESS';

// Updating dm tasks rank and text when save is clicked.
export const UPDATE_DM_TASK_PENDING = 'UPDATE_DM_TASK_PENDING';
export const UPDATE_DM_TASK_SUCCESS = 'UPDATE_DM_TASK_SUCCESS';
export const UPDATE_DM_TASK_FAILED = 'UPDATE_DM_TASK_FAILED';

export const CHANGE_DM_TASK_EDITING = 'CHANGE_DM_TASK_EDITING';