export const REQUEST_DM_TASKS_PENDING = 'REQUEST_DM_TASKS_PENDING';
export const REQUEST_DM_TASKS_SUCCESS = 'REQUEST_DM_TASKS_SUCCESS';
export const REQUEST_DM_TASKS_FAILED = 'REQUEST_DM_TASKS_FAILED';

export const CHANGE_DM_EDITING = 'CHANGE_DM_EDITING'