export const SUBMIT_CBT_EVENT_PENDING = "SUBMIT_CBT_EVENT_PENDING";
export const SUBMIT_CBT_EVENT_SUCCESS = "SUBMIT_CBT_EVENT_SUCCESS";
export const SUBMIT_CBT_EVENT_FAILED = "SUBMIT_CBT_EVENT_FAILED";

export const GET_CBT_EVENTS_PENDING = "GET_CBT_EVENTS_PENDING";
export const GET_CBT_EVENTS_SUCCESS = "GET_CBT_EVENTS_SUCCESS";
export const GET_CBT_EVENTS_FAILED = "GET_CBT_EVENTS_FAILED";
