export const SUBMIT_CBT_EVENT_PENDING = "SUBMIT_CBT_EVENT_PENDING";
export const SUBMIT_CBT_EVENT_SUCCESS = "SUBMIT_CBT_EVENT_SUCCESS";
export const SUBMIT_CBT_EVENT_FAILED = "SUBMIT_CBT_EVENT_FAILED";
